### ISSUE TITLE
ant.design 希望能提供直接可以使用的js, 不翻墙搭建环境都不成功

### ISSUE THREAD

**Issue by ywww** [alipay/x#12]
ant.design 希望能提供直接可以使用的js, 不翻墙搭建环境都不成功, 谢谢

**Comment by ywww** [comment]
[root@server200 ant-design-0.10.4]# npm install webpack
npm http GET https://registry.npmjs.org/webpack
^C[root@server200 ant-design-0.10.4]# npm install webpack -g
npm http GET https://registry.npmjs.org/webpack
npm http GET https://registry.npmjs.org/webpack
npm http GET https://registry.npmjs.org/webpack
npm ERR! network socket hang up
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network 
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! System Linux 2.6.32-279.el6.x86_64
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "webpack" "-g"
npm ERR! cwd /usr/local/src/ant-design-0.10.4
npm ERR! node -v v0.10.18
npm ERR! npm -v 1.3.8
npm ERR! code ECONNRESET
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /usr/local/src/ant-design-0.10.4/npm-debug.log
npm ERR! not ok code 0

**Comment by afc163** [comment]
https://npm.taobao.org/

**Comment by fengmk2** [comment]
不翻墙能做好技术活吗？

**Comment by xudafeng** [comment]
不翻墙能做好技术活吗？

**Comment by asxu** [comment]
小白很吃力。很是痛苦。。。。

**Comment by lichungod** [comment]
用ss很容易就能翻了，不翻墙绝对不能做好技术活，翻墙的成本已经很低，没有理由不翻
