### ISSUE TITLE
支付宝体验技术部海纳百川招聘啦~

### ISSUE THREAD

**Issue by lifesinger** [alipay/x#3]
## 有这么一个团队

他们所做的事情，是技术与艺术的结合。页面的每一个像素，都有他们深雕细琢的付出。

他们所做的事情，把简单、快捷留给用户，烦琐、挑战的技术实现留给自己。从密码控件支持 TAB 操作，到二维码扫码登录。

他们所做的事情，分分钟都在为上亿人服务。从 PC 端到移动端，无处不在。

他们是理性派，追求技术上的专业和深度。 以开放的姿态研究和分享新技术，以简单的理念设计和开发产品，以用户的角度去完善和优化。

他们崇尚有爱，脑子灵光、生活中不乏小文艺。上能写得了代码，下能做得了木工，左能唱得起 High 歌，右能钓得到江鱼。

而我，就是他们中的一员。我们并不只他们，还有你，期待你的到来！

## 充满机会的一年

新的一年里，支付宝体验技术部将更加多元化：

我们不只在 PC 端玩代码，我们还会涉及移动端（Android 和 iOS），甚至是电视端、家电端，浏览器端已经不能满足我们，请叫我们全端工程师。

我们不只在浏览器端玩代码，我们还会在服务器端玩 Node、Java 等等，我们玩运维、玩网络，从端到云地变化，我们将会是新时代的全栈工程师。

我们也招聘交互和视觉设计师，我们期待才华横溢的你能加入我们，一起来实现梦想中的产品。

在这里，你不光可以走得很快，还可以协同团队一起走得更远，去那未曾到过的美丽远方。

## 海纳百川

2014 年，我们长期招聘以下岗位：

1. **前端工程师**。 期待往全端方向发展，或期待往全栈方向发展的你，就是我们想要的。

1. **交互或视觉设计师**。 负责支付宝互联网支付、金融、数据等产品的交互或视觉设计，我们希望你在设计方面是专家，同时懂产品，懂前端代码更佳。我们相信你的存在。

1. **Java 工程师**。我们的兄弟团队是支付宝 Java 中间件团队，每秒支持几万笔交易，是互联网金融领域最有技术含量的 Java 队伍。

我们看重激情、潜力，没有任何学历、工作经历等限制，我们期待最优秀的你。

如果你能阅读到这里，说明你就是我们想要的，请发送简历到：yubo@alipay.com
补充工作地点：以杭州为主，如果你足够优秀，也可以选择成都、上海、北京作为办公地点。

![](http://ww4.sinaimg.cn/mw1024/68361562gw1ednn4acjyfj20fn0figom.jpg)

---

> 做地球上专业、有爱的团队。

**Comment by photino** [comment]
@lifesinger 玉伯兄，你好！我想今年申请阿里支付宝前端，能不能和你聊聊呢？谢谢！

**Comment by xingfuqiu** [comment]
能在成都工作就不错了,可以和@huacnlee一起

**Comment by Suixinlei** [comment]
16年毕业，第一次学的语言就是node，中途各种语言都了解了解，但是还是我js最好。现在在阿里实习，希望正式入职的时候能进入玉伯那边的团队的

**Comment by sakyaer** [comment]
千里之行，始于足下。阿里，西湖 梦想的地方。

**Comment by jameBoy** [comment]
不更新了么，干货呢？

**Comment by coldhand** [comment]
自由职业者

**Comment by sequoiar** [comment]
@coldhand 兼职考虑吗？

**Comment by coldhand** [comment]
@sequoiar 考虑的
