### ISSUE TITLE
一点也不开发者友好！！！！！！！！！！

### ISSUE THREAD

**Issue by fmyzjs** [alipay/x#6]
-  能像paypal/CyberSource一样给一个开发者sandbox站点么？
-  能给点像样点的官方的文档齐全品种齐全的sdk么？
-  能开放给个人开发者么？
-  你们是在无聊么，github组织建立了，到现在连一个装样子的项目都没有！！

**Comment by afc163** [comment]
...这是在吐槽啥，都没有看懂。

**Comment by fmyzjs** [comment]
吐槽alipay糟糕的开发者体验

**Comment by popomore** [comment]
我以为看错了，这个库还有存在的必要么

**Comment by afc163** [comment]
这个组织都不是官方的，建议到 Alipay 的客服去吐槽效果更佳。

**Comment by fmyzjs** [comment]
如我所言，你们可以去申请paypal/CyberSource 开发者，看看别人提供了什么，你们提供了什么。

**Comment by afc163** [comment]
这里是前端团队，其实我们也招后端，欢迎投简历。:smile: 虽然我们实际上不负责开放平台。

**Comment by jsw0528** [comment]
感叹号正好十个
