### ISSUE TITLE
能改的再蛋疼点么

### ISSUE THREAD

**Issue by kxjhwbb** [alipay/x#9]
支付页面原本是可以直接从其他页面提交参数过来快速生成转账单子的，你们现在把这东西废了，我不知道用意何在？  这样一来我平台提现操作本来一个按钮可以完成的工作，现在只能复制3次来完成

**Comment by fengmk2** [comment]
具体是怎样操作的？

**Comment by kxjhwbb** [comment]
@fengmk2 

`<form method="post" action="https://shenghuo.alipay.com/send/payment/fill.htm" accept-charset="GBK" onsubmit="document.charset='GBK'" target="_blank">`
`<input value="支付宝账号" name="optEmail" type="hidden">`
`<input value="提现IDXXX" name="title" type="hidden">`
`<input value="提现金额" name="payAmount" type="hidden">`
`<input value="实名" name="inputRealName" type="hidden">`
`<input type="submit" value="跳转支付宝">`
`</form>`

现在不行了，转账页面先是判断了referer，然后是把参数传入input废了。。  即便我在浏览器改了referer，也只有title值能够穿到转账页面的转账说明里，现在只好用F12来搞了..

**Comment by kxjhwbb** [comment]
我也是在F12的console里看到这个github链接的。。

**Comment by kxjhwbb** [comment]
支付宝能不能搞一个转账接口什么的？  否则有用支付宝提现需求的很蛋疼。。只能一个个去转账

**Comment by kxjhwbb** [comment]
还有一些非常神奇的问题，例如这个支付宝账号：492574921@qq.com，如果用普通转账，是完全正常的，如果用支付宝自带的向多人付款功能，那么就会提示未实名认证了。。
